# Generated by Django 5.2.12 on 2026-03-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_total', models.CharField(blank=True, max_length=100, null=True)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
    ]
